### ISSUE TITLE
system catalog changes in Postgres 11

### ISSUE THREAD

**Issue by bricklen** [microsoft/pgtoolsservice#209]
When connecting to Postgresql 11, the queries for function definitions (pg_catalog.pg_proc) are out of date, and thus fail to load.

Eg. https://github.com/Microsoft/pgtoolsservice/blob/master/pgsmo/objects/functions/templates_functions/pg/+default/nodes.sql#L28

An example of how pgadmin has fixed this can be found at 
https://github.com/postgres/pgadmin4/blob/master/web/pgadmin/browser/server_groups/servers/databases/schemas/functions/templates/functions/pg/sql/11_plus/node.sql

**Comment by akamath46297** [comment]
@bricklen , thanks for reporting the issue. We currently have few other issue w.r.t PG 11 which we will be fixing.

**Comment by nasc17** [comment]
![image](https://github.com/microsoft/pgtoolsservice/assets/69922333/938ac9ea-91d0-4bde-b8b5-2d3da669d00f)
