### ISSUE TITLE
Update to v1.3.0 clears saved passwords

### ISSUE THREAD

**Issue by BraveThrasher** [microsoft/pgtoolsservice#230]
This morning Azure Data Studio automatically installed version 1.3.0 of pgtoolsservice. 
When I try to open my saved connections for which I also have the passwords saved I get the following connection error "fe_sendauth: no password supplied"
Looking at the connection information I notice that the update apparently cleared all the password fields and remember password check-boxes.

**Comment by nasc17** [comment]
![image](https://github.com/microsoft/pgtoolsservice/assets/69922333/277cbc44-12b3-4ad4-b3ed-bf46caac5cd2)
