### ISSUE TITLE
column rel.relhasoids does not exist

### ISSUE THREAD

**Issue by Bowside** [microsoft/pgtoolsservice#281]
Azure Data Studio - 1.28
PostgreSQL extension - 0.2.7
PGToolsService - 1.5
Postgres - 12.7

When trying to script out an existing table from within Azure Data Studio, you get an error stating the following;
  Code: 0 
[object Object]
[Error - 14:02:33] Request scripting/script failed.
  Message: column rel.relhasoids does not exist
LINE 8:   pg_get_userbyid(rel.relowner) AS relowner, rel.relhasoids,

Upon further investigation the issue is to do with this -  https://postgresql.verite.pro/blog/2019/04/24/oid-column.html

Commenting out the column in the following file resolves the issue; https://github.com/microsoft/pgtoolsservice/blob/master/pgsmo/objects/table/templates/9.1_plus/properties.sql 

However I suspect that is more of a hack than a fix.

**Comment by daghb** [comment]
https://github.com/microsoft/azuredatastudio-postgresql/issues/225

**Comment by nasc17** [comment]
Bug has been addressed in latest stable release of PostgreSQL extension v0.4.1 using pgtoolsservice v1.8.0. Please reopen if issue persists, thank you.
