### ISSUE TITLE
Cannot open database list in Azure Data Studio 

### ISSUE THREAD

**Issue by jonashilmersson** [microsoft/pgtoolsservice#353]
An error occurs in Azure Data Studio (as described here https://github.com/microsoft/azuredatastudio-postgresql/issues/333) when trying to expand the database node for Postgres later than v14.  As noted in a related issue, it can be fixed by updating the nodes.sql file from the ossdbtoolsservice found in this repo.

https://github.com/microsoft/azuredatastudio-postgresql/issues/334#issuecomment-1348843050

Could we get an update here that fixes the problem for Azure Data Studio?

**Comment by DaeunYim** [comment]
Being tracked in https://github.com/microsoft/azuredatastudio-postgresql/issues/357. Closing the issue
