### ISSUE TITLE
Error: "PostgreSQL Tools Service component could not start"

### ISSUE THREAD

**Issue by DavidS** [microsoft/pgtoolsservice#454]
Upon installing the extension and trying the "New Query" command I get this error:

![2023-07-30_09MS+0200_573x162](https://github.com/microsoft/pgtoolsservice/assets/27712/18d6492f-4fe2-402a-bd9e-424aaf00609e)

and this log from the SqlToolsService initialization:

```
Initializing PostgreSQL tools service for the PostgreSQL extension.
Note: PostgreSQL commands will be available after installing the service.

Platform-------------: linux, x86_64, name=debian, version=12 (Debian)


Installing PostgreSQL tools service to /home/vscode/.vscode-server/extensions/ms-ossdata.vscode-postgresql-0.3.0/pgsqltoolsservice/v1.4.0/Debian.
Downloading https://github.com/Microsoft/pgtoolsservice/releases/download/v1.4.0/pgsqltoolsservice-linux-x64.tar.gz
(21369 KB) .................... Done!
Installing ...
Done! 1804 files unpacked.
```

no query editor shows up.

# Environment

devcontainer: mcr.microsoft.com/devcontainers/rust:1-1-bookworm

**Comment by nasc17** [comment]
Hi, can you please provide us the name and about information of the tool you are using, as well as the version of the PostgreSQL extension who have installed.
